nat64.c
tayga.c
tayga.h

Merges patch from Freebsd to support BSD in addition to Linux
Source:
https://raw.githubusercontent.com/freebsd/freebsd-ports/refs/heads/main/net/tayga/files/patch-freebsd

Merge freebsd patch

---

test/addressing.py
test/test_env.py
test/translate.py

Several test cases need to merge

Updated tests

---

test/mapping.py
test/test_env.py

Resolves #15 (test cases are complete, code is not resolved)
Resolves #36 (test cases are complete, code is not resolved)
Resolves #2

Mapping Tests

---

README.md

Document RFC compliance

---

nat64.c
test/translate.py

Resolve ICMP fake-source

---

nat64.c
test/translate.py

Resolves #20 
Does not cause any test failures, however, I am not convinced it is entirely bug free.

ICMP Extension Parsing

---

nat64.c
test/translate.py

Reverts apalrd/tayga#49
Needs more discussion on if we should implement this

Revert "ICMP Extension Parsing"

---

Makefile
tayga.h

Fixed dummy func error

---

conffile.c
tayga.c
tayga.h
test/translate.py

Cleanup conf file code

---

nat64.c
test/translate.py

V4->V6 Inner Translation

---

test/translate.py

V6->V4 Inner Translation

---

conffile.c
nat64.c
tayga.conf.example
tayga.h
test/translate.py

Zero UDP Checksum behavior

---

test/translate.py

Section 5.1 test

---

addrmap.c
conffile.c
dynamic.c
nat64.c
tayga.c
tayga.conf.5
tayga.conf.example
tayga.h
test/test_env.py

Implement packet drop/reject logging

---

nat64.c
tayga.h

Resolve clang warnings

---

conffile.c
tayga.conf.5
tayga.conf.example
test/test_env.py
test/translate.py

Allow configuration of offlink-mtu per #96

Offlink MTU Configuration

---

Makefile
scripts/tayga.confd
scripts/tayga.initd

Should be available to Gentoo and Alpine.
Still untested, looking for feedback here

OpenRC init script

---

conffile.c
nat64.c
tayga.conf.5
tayga.h
test/unit_conffile.c

remove strict frag header and related code

---

Makefile

Make install should create system directories if they do not exist

Make directories that don't exist

---

.github/workflows/basic.yml
.github/workflows/release.yml
.github/workflows/tests.yml
Makefile

Improve Github Actions

---

.github/workflows/basic.yml
Makefile
tayga.c

Basic Test action now does gcc + clang

Basic Test

---

tayga.c

The PR I previously made uses `--user` and `--group` with `--mktun`, but is potentially unsafe as forgetting one of the flags makes the interface world-readable.
This commit uses `root:root` if neither flag is used.

Ensure tun interface has owner or group permissions

---

conffile.c
docs/index.md
dynamic.c
tayga.conf.example
tayga.h
test/unit_conffile.c

Log dynamic pool assignments
